language: python
cache: pip
matrix:
  include:
  - os: osx
    language: generic
  - python: pypy
  - python: 2.7
  - python: 3.5
  - python: 3.6
install:
  - scripts/install-on-travis.sh
script:
  - scripts/run-on-travis.sh make check
  - scripts/run-on-travis.sh make test
after_success:
  - scripts/run-on-travis.sh coveralls
branches:
  except:
    - /^[0-9]/
